### ISSUE TITLE
Hardcoded pytest-3 expected by runtest.py

### ISSUE THREAD

**Issue by pkgdemon** [pkgdemon/api-test-runner#2]
```root@84c0e5298e75:/# python3 /mnt/middleware/tests/runtest.py --ip 192.168.1.66 --password testing --interface eth0
^[[3~Identity added: /root/.ssh/test_id_rsa (root@84c0e5298e75)
Traceback (most recent call last):
  File "/mnt/middleware/tests/runtest.py", line 170, in <module>
    call([
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pytest-3'

**Comment by pkgdemon** [comment]
https://github.com/pkgdemon/api-test-runner/commit/c86122081ee1743f0228b41b02b2742504178c71
